package service;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-24T23:32:34.859+08:00
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://jw.nju.edu.cn/wsdl", name = "stuScoreInterface")
public interface StuScoreInterface {
}
