
package cn.edu.nju.soa.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-26T19:43:55.927+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "AuthFault", targetNamespace = "http://jw.nju.edu.cn/schema")
public class PswErrorFault extends Exception {

    private cn.edu.nju.jw.schema.AuthFaultType authFault;

    public PswErrorFault() {
        super();
    }

    public PswErrorFault(String message) {
        super(message);
    }

    public PswErrorFault(String message, Throwable cause) {
        super(message, cause);
    }

    public PswErrorFault(String message, cn.edu.nju.jw.schema.AuthFaultType authFault) {
        super(message);
        this.authFault = authFault;
    }

    public PswErrorFault(String message, cn.edu.nju.jw.schema.AuthFaultType authFault, Throwable cause) {
        super(message, cause);
        this.authFault = authFault;
    }

    public cn.edu.nju.jw.schema.AuthFaultType getFaultInfo() {
        return this.authFault;
    }
}
