
package cn.edu.nju.soa.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-26T16:58:43.743+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "InvalidParamFault", targetNamespace = "http://jw.nju.edu.cn/schema")
public class ScoreUpdateFault extends Exception {

    private cn.edu.nju.jw.schema.ParamFaultType invalidParamFault;

    public ScoreUpdateFault() {
        super();
    }

    public ScoreUpdateFault(String message) {
        super(message);
    }

    public ScoreUpdateFault(String message, Throwable cause) {
        super(message, cause);
    }

    public ScoreUpdateFault(String message, cn.edu.nju.jw.schema.ParamFaultType invalidParamFault) {
        super(message);
        this.invalidParamFault = invalidParamFault;
    }

    public ScoreUpdateFault(String message, cn.edu.nju.jw.schema.ParamFaultType invalidParamFault, Throwable cause) {
        super(message, cause);
        this.invalidParamFault = invalidParamFault;
    }

    public cn.edu.nju.jw.schema.ParamFaultType getFaultInfo() {
        return this.invalidParamFault;
    }
}
