
package cn.edu.nju.soa.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-26T16:58:43.768+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "InvalidParamFault", targetNamespace = "http://soa.nju.edu.cn/model")
public class ScoreTypeFault extends Exception {

    private cn.edu.nju.soa.model.ParamFaultType invalidParamFault;

    public ScoreTypeFault() {
        super();
    }

    public ScoreTypeFault(String message) {
        super(message);
    }

    public ScoreTypeFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public ScoreTypeFault(String message, cn.edu.nju.soa.model.ParamFaultType invalidParamFault) {
        super(message);
        this.invalidParamFault = invalidParamFault;
    }

    public ScoreTypeFault(String message, cn.edu.nju.soa.model.ParamFaultType invalidParamFault, java.lang.Throwable cause) {
        super(message, cause);
        this.invalidParamFault = invalidParamFault;
    }

    public cn.edu.nju.soa.model.ParamFaultType getFaultInfo() {
        return this.invalidParamFault;
    }
}
