
package cn.edu.nju.soa.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-26T19:06:38.478+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "NotFoundFault", targetNamespace = "http://jw.nju.edu.cn/schema")
public class StudentIdFault extends Exception {

    private cn.edu.nju.jw.schema.NotFoundType notFoundFault;

    public StudentIdFault() {
        super();
    }

    public StudentIdFault(String message) {
        super(message);
    }

    public StudentIdFault(String message, Throwable cause) {
        super(message, cause);
    }

    public StudentIdFault(String message, cn.edu.nju.jw.schema.NotFoundType notFoundFault) {
        super(message);
        this.notFoundFault = notFoundFault;
    }

    public StudentIdFault(String message, cn.edu.nju.jw.schema.NotFoundType notFoundFault, Throwable cause) {
        super(message, cause);
        this.notFoundFault = notFoundFault;
    }

    public cn.edu.nju.jw.schema.NotFoundType getFaultInfo() {
        return this.notFoundFault;
    }
}
