
package cn.edu.nju.soa.wsdl;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-26T16:58:43.726+08:00
 * Generated source version: 3.2.3
 */

@WebFault(name = "NotFoundFault", targetNamespace = "http://soa.nju.edu.cn/model")
public class StudentIdFault extends Exception {

    private cn.edu.nju.soa.model.NotFoundType notFoundFault;

    public StudentIdFault() {
        super();
    }

    public StudentIdFault(String message) {
        super(message);
    }

    public StudentIdFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public StudentIdFault(String message, cn.edu.nju.soa.model.NotFoundType notFoundFault) {
        super(message);
        this.notFoundFault = notFoundFault;
    }

    public StudentIdFault(String message, cn.edu.nju.soa.model.NotFoundType notFoundFault, java.lang.Throwable cause) {
        super(message, cause);
        this.notFoundFault = notFoundFault;
    }

    public cn.edu.nju.soa.model.NotFoundType getFaultInfo() {
        return this.notFoundFault;
    }
}
