package cn.edu.nju.soa.wsdl;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-26T19:06:38.672+08:00
 * Generated source version: 3.2.3
 *
 */
@WebServiceClient(name = "stuInfoService",
                  wsdlLocation = "file:./wsdl/StuInfo.wsdl",
                  targetNamespace = "http://jw.nju.edu.cn/wsdl")
public class StuInfoService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://jw.nju.edu.cn/wsdl", "stuInfoService");
    public final static QName StuInfoEndpoint = new QName("http://jw.nju.edu.cn/wsdl", "stuInfoEndpoint");
    static {
        URL url = null;
        try {
            url = new URL("file:./wsdl/StuInfo.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(StuInfoService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:./wsdl/StuInfo.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public StuInfoService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StuInfoService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StuInfoService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public StuInfoService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public StuInfoService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public StuInfoService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns StuInfoInterface
     */
    @WebEndpoint(name = "stuInfoEndpoint")
    public StuInfoInterface getStuInfoEndpoint() {
        return super.getPort(StuInfoEndpoint, StuInfoInterface.class);
    }

    /**
     *
     * @param features
     *     A list of {@link WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StuInfoInterface
     */
    @WebEndpoint(name = "stuInfoEndpoint")
    public StuInfoInterface getStuInfoEndpoint(WebServiceFeature... features) {
        return super.getPort(StuInfoEndpoint, StuInfoInterface.class, features);
    }

}
