package cn.edu.nju.soa.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-26T19:06:38.636+08:00
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://jw.nju.edu.cn/wsdl", name = "StuInfoInterface")
@XmlSeeAlso({cn.edu.nju.schema.ObjectFactory.class, cn.edu.nju.jw.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StuInfoInterface {

    @WebMethod(action = "student/addStudent")
    @Action(input = "student/addStudentRequest", output = "student/addStudentResponse", fault = {@FaultAction(className = StudentIdFault.class, value = "student/addStudent/Fault/StudentIdFaultException"), @FaultAction(className = BasicMessageFault.class, value = "student/addStudent/Fault/BasicMessageFaultException"), @FaultAction(className = CourseIdFault.class, value = "student/addStudent/Fault/CourseIdFaultException")})
    public void addInfo(
            @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "学生信息", targetNamespace = "http://jw.nju.edu.cn/schema")
                    javax.xml.ws.Holder<cn.edu.nju.jw.schema.学生信息类型> parameters
    ) throws StudentIdFault, BasicMessageFault, CourseIdFault;

    @WebMethod(action = "student/modifyStudent")
    @Action(input = "student/modifyStudentRequest", output = "student/modifyStudentResponse", fault = {@FaultAction(className = StudentIdFault.class, value = "student/modifyStudent/Fault/StudentIdFaultException"), @FaultAction(className = BasicMessageFault.class, value = "student/modifyStudent/Fault/BasicMessageFaultException"), @FaultAction(className = CourseIdFault.class, value = "student/modifyStudent/Fault/CourseIdFaultException")})
    public void modifyInfo(
            @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "学生信息", targetNamespace = "http://jw.nju.edu.cn/schema")
                    javax.xml.ws.Holder<cn.edu.nju.jw.schema.学生信息类型> parameters
    ) throws StudentIdFault, BasicMessageFault, CourseIdFault;

    @WebMethod(action = "student/getStudent")
    @Action(input = "student/getStudentRequest", output = "student/getStudentResponse", fault = {@FaultAction(className = IdNotFindFault.class, value = "student/getStudent/Fault/IdNotFoundException")})
    @WebResult(name = "学生信息", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public cn.edu.nju.jw.schema.学生信息类型 getInfo(
            @WebParam(partName = "parameters", name = "学号", targetNamespace = "http://jw.nju.edu.cn/schema")
                    String parameters
    ) throws IdNotFindFault;

    @WebMethod(action = "student/deleteStudent")
    @Action(input = "student/deleteStudentRequest", output = "student/deleteStudentResponse", fault = {@FaultAction(className = StudentIdFault.class, value = "student/deleteStudent/Fault/StudentIdFaultException"), @FaultAction(className = BasicMessageFault.class, value = "student/deleteStudent/Fault/BasicMessageFaultException"), @FaultAction(className = CourseIdFault.class, value = "student/deleteStudent/Fault/CourseIdFaultException")})
    @WebResult(name = "学生信息", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public cn.edu.nju.jw.schema.学生信息类型 delInfo(
            @WebParam(partName = "parameters", name = "学号", targetNamespace = "http://jw.nju.edu.cn/schema")
                    String parameters
    ) throws StudentIdFault, BasicMessageFault, CourseIdFault;
}
