<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!--<wsdl:definitions -->
  <!--xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" -->
  <!--xmlns:tns="http://jw.nju.edu.cn/StuInfo/" -->
  <!--xmlns:fault="http://jw.nju.edu.cn/fault/wsdl"-->
  <!--xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" -->
  <!--xmlns:xsd="http://www.w3.org/2001/XMLSchema" -->
  <!--name="StuInfoService" targetNamespace="http://jw.nju.edu.cn/wsdl">-->

<definitions
        targetNamespace="http://jw.nju.edu.cn/wsdl"
        xmlns:tns="http://jw.nju.edu.cn/wsdl"
        xmlns:nju="http://www.nju.edu.cn/schema"
        xmlns:tns1="http://jw.nju.edu.cn/schema"
        xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
        xmlns:wsam="http://www.w3.org/2007/05/addressing/metadata"
        xmlns:xsd="http://www.w3.org/2001/XMLSchema"
        xmlns="http://schemas.xmlsoap.org/wsdl/"
        name="StudentService">

  <documentation>学生个人信息管理服务</documentation>
  
  <!--<import namespace="http://jw.nju.edu.cn/fault/wsdl" location="StuInfoFault.wsdl">-->
	
  <types>
    <xsd:import
			namespace="http://jw.nju.edu.cn/schema"
			schemaLocation="xsd/Student.xsd" />


	<xsd:import
			namespace="http://jw.nju.edu.cn/schema"
			schemaLocation="xsd/StuInfoFault.xsd" />
  </types>
  
  <portType name="StuInfoInterface" extends="fault:stuFaultInterface">
    <operation name="getInfo">
      <input messageLabel="In" element="tns:学号"/>
      <output messageLabel="out" message="tns:学生信息"/>
      <fault ref="fault:idNotFoundFault" messageLabel="Out" />
    </operation>
    
    <operation name="addInfo">
      <input messageLabel="In" element="tns:学生信息"/>
      <output messageLabel="out" message="tns:学生信息"/>
      <fault ref="fault:studentIdFault" messageLabel="Out" />
	  <fault ref="fault:courseIdFault" messageLabel="Out" />
	  <fault ref="fault:basicMessageFault" messagLabel="Out">
    </operation>
    
    <operation name="delInfo">
      <input messageLabel="In" element="tns:学号"/>
      <output messageLabel="out" message="tns:学生信息"/>
      <fault ref="fault:studentIdFault" messageLabel="Out" />
	  <fault ref="fault:courseIdFault" messageLabel="Out" />
	  <fault ref="fault:basicMessageFault" messagLabel="Out">
    </operation>
    
    <operation name="modifyInfo">
      <input messageLabel="In" element="tns:学生信息"/>
      <output messageLabel="out" message="tns:学生信息"/>
      <fault ref="fault:studentIdFault" messageLabel="Out" />
	  <fault ref="fault:courseIdFault" messageLabel="Out" />
	  <fault ref="fault:basicMessageFault" messagLabel="Out">
    </operation>
  </portType>
  
  <binding
    name="StuInfoSOAP" interface="tns:StuInfoInterface"
	type="http://www.w3.org/ns/wsdl/soap"
	wsoap:protocol="http://www.w3.org/2003/05/soap/bindings/HTTP/">
	
    <operation ref="tns:getInfo"
			wsoap:mep="http://www.w3.org/2003/05/soap/mep/soap-response" />
	<operation ref="tns:addInfo"
			wsoap:mep="http://www.w3.org/2003/05/soap/mep/request-response" />
	<operation ref="tns:delInfo"
			wsoap:mep="http://www.w3.org/2003/05/soap/mep/soap-response" />
	<operation ref="tns:modifyInfo"
			wsoap:mep="http://www.w3.org/2003/05/soap/mep/reauest-response" />
    
    <fault ref="fault:idNotFoundFault" wsoap:code="soap:Sender" />
    <fault ref="fault:studentIdFault" wsoap:code="soap:Sender" />
	<fault ref="fault:courseIdFault" wsoap:code="soap:Sender" />
	<fault ref="fault:basicMessageFault" wsoap:code="soap:Sender"/>
  </binding>
  
  <service name="StuInfoService" interface="tns:stuScoreInterface">
    <endpoint name="StuInfoInterface" binding="tns:StuInfoSOAP" address="http://www.nju.edu.cn:8080/stuInfo">
  </service>

</definitions>
