package cn.edu.nju.jw.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.FaultAction;

/**
 * This class was generated by Apache CXF 3.2.3
 * 2018-03-25T23:36:51.067+08:00
 * Generated source version: 3.2.3
 *
 */
@WebService(targetNamespace = "http://jw.nju.edu.cn/wsdl", name = "stuScoreInterface")
@XmlSeeAlso({cn.edu.nju.schema.ObjectFactory.class, cn.edu.nju.jw.schema.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface StuScoreInterface {

    @WebMethod(action = "score/getScore")
    @Action(input = "score/getScoreRequest", output = "score/getScoreResponse", fault = {@FaultAction(className = IdNotFindFault.class, value = "score/getScore/Fault/IdNotFoundException")})
    @WebResult(name = "课程成绩列表", targetNamespace = "http://jw.nju.edu.cn/schema", partName = "parameters")
    public cn.edu.nju.jw.schema.课程成绩列表类型 get(
            @WebParam(partName = "parameters", name = "学号", targetNamespace = "http://jw.nju.edu.cn/schema")
                    String parameters
    ) throws IdNotFindFault;
}
